[splash]
current = "moka-short-hair"

[status]
menu_battery = true
menu_wifi = true
menu_bluetooth = true
menu_show_percent = true
menu_charging = true
menu_background = "black"
splash_battery = true
splash_wifi = true
splash_bluetooth = true
splash_show_percent = false
splash_charging = true
splash_background = "black"
splash_position = "top_center"
splash_order = "battery_wifi_bt"

[wifi_setup]
ap_ssid = "KeyCrow-Setup"
ap_password = "keycrow123"
portal_ip = "10.42.0.1"
portal_port = 8080

[music]
bt_mac = "C6:AE:E3:35:6F:0B"
output = "bluetooth"
